### ISSUE TITLE
License file

### ISSUE THREAD

**Issue by jekh** [ganskef/LittleProxy-mitm#1]
Thanks for this excellent demonstration of MITM with LP. Could you add a LICENSE.txt file to make the license explicit? FWIW, LittleProxy is under the [Apache 2.0 License](https://github.com/adamfisk/LittleProxy/blob/master/LICENSE.txt). (Did you use any GPL code or libraries? That might require you to publish the entire work under the GPL.)

I ask because I'd really like to help better-integrate this with the main LP and, eventually, BrowserMob Proxy. It'd be great to be able to make modifications, submit PRs to you, and hopefully cherry-pick code into LP itself.

Thanks again! This is fantastic.

**Comment by ganskef** [comment]
My pleasure! I've introduced no additionally dependencies. BouncyCastle is in testing scope allready.

**Comment by jekh** [comment]
Awesome! Thank you, @ganskef. All my spare time has been spent trying to get the next BMP beta out the door, but that is going to happen "very soon", and then I'll dig into this.
