### ISSUE TITLE
CertificateSniffingMitmManager throws exceptions if upstreamCert.getSubjectAlternativeNames() is null

### ISSUE THREAD

**Issue by rhehl** [ganskef/LittleProxy-mitm#11]
Fix:

String commonName = getCommonName(upstreamCert);

			SubjectAlternativeNameHolder san = new SubjectAlternativeNameHolder();

			Collection<List<?>> an = upstreamCert.getSubjectAlternativeNames();

			if (an == null) {
				san = new SubjectAlternativeNameHolder();
			} else {
				san.addAll(an);
			}

			LOG.debug("Subject Alternative Names: {}", san);
			return sslEngineSource.createCertForHost(commonName, san);

**Comment by ganskef** [comment]
Hi @rhehl , thank you for your attention. The upstream cert could return a null SAN list. 

I think the ```addAll()``` method better should handle (ignore) a null value. I'm going to create a branch/PR for this. (Or, I would merge yours, if you like.)

**Comment by ganskef** [comment]
It's integrated now, so I close this issue.

**Comment by vikasguptahk** [comment]
I want to build an application using littleproxy-mitm that can handle https transparent proxy, can u suggest how to do , I am getting No Availaible authentication scheme
