### ISSUE TITLE
Android only handshake_failure with different cdn sites

### ISSUE THREAD

**Issue by ganskef** [ganskef/LittleProxy-mitm#17]
I'm searching for a while for a volatile problem (using my [Mo Cuishle](https://ganskef.github.io/MoCuishle/android-install/) app): Secured connections are terminated with some different sites with some different devices. The content is shown but without its page style. I've never seen it with a desktop system. Please, has anybody some ideas, device examples, debug strategies?  
- Nexus 5, Android 6.0.1 (N) fails with https://assets-cdn.github.com, works fine in emulator
- Samsung i9300, Android 4.4.4 fails with https://developer.cdn.mozilla.net, fails in emulator too

Both devices are showing the other site with no problems. I'm pretty sure it's deterministic. It seems not to depend on Netty versions.

This is a typical `adb logcat` output:

<pre>
D/org.littleshoot.proxy.impl.ClientToProxyConnection( 2897): [MoCuishle-0-ClientToProxyWorker-0] (AWAITING_INITIAL) [id: 0xf0297475, /127.0.0.1:39401 => /127.0.0.1:9090]: Not reusing existing ProxyToServerConnection because request is a CONNECT for: developer.cdn.mozilla.net:443
D/org.littleshoot.proxy.impl.ClientToProxyConnection( 2897): [MoCuishle-0-ClientToProxyWorker-0] (AWAITING_INITIAL) [id: 0xf0297475, /127.0.0.1:39401 => /127.0.0.1:9090]: Modifying request for proxy chaining
D/org.littleshoot.proxy.impl.ClientToProxyConnection( 2897): [MoCuishle-0-ClientToProxyWorker-0] (AWAITING_INITIAL) [id: 0xf0297475, /127.0.0.1:39401 => /127.0.0.1:9090]: Stripped host from uri: developer.cdn.mozilla.net:443    yielding: developer.cdn.mozilla.net:443
D/org.littleshoot.proxy.impl.ClientToProxyConnection( 2897): [MoCuishle-0-ClientToProxyWorker-0] (AWAITING_INITIAL) [id: 0xf0297475, /127.0.0.1:39401 => /127.0.0.1:9090]: Modifying request headers for proxying
D/org.littleshoot.proxy.impl.ClientToProxyConnection( 2897): [MoCuishle-0-ClientToProxyWorker-0] (AWAITING_INITIAL) [id: 0xf0297475, /127.0.0.1:39401 => /127.0.0.1:9090]: Writing request to ProxyToServerConnection
D/org.littleshoot.proxy.impl.ProxyToServerConnection( 2897): [MoCuishle-0-ClientToProxyWorker-0] (DISCONNECTED): Requested write of DefaultHttpRequest(decodeResult: success, version: HTTP/1.1)
D/org.littleshoot.proxy.impl.ProxyToServerConnection( 2897): CONNECT developer.cdn.mozilla.net:443 HTTP/1.1
D/org.littleshoot.proxy.impl.ProxyToServerConnection( 2897): User-Agent: Mozilla/5.0 (Android 4.4.4; Mobile; rv:45.0) Gecko/45.0 Firefox/45.0
D/org.littleshoot.proxy.impl.ProxyToServerConnection( 2897): Host: developer.cdn.mozilla.net:443
D/org.littleshoot.proxy.impl.ProxyToServerConnection( 2897): Via: 1.1 littleproxy
D/org.littleshoot.proxy.impl.ProxyToServerConnection( 2897): [MoCuishle-0-ClientToProxyWorker-0] (DISCONNECTED): Currently disconnected, connect and then write the message
D/org.littleshoot.proxy.impl.ProxyToServerConnection( 2897): [MoCuishle-0-ClientToProxyWorker-0] (DISCONNECTED): Starting new connection to: developer.cdn.mozilla.net/54.240.162.197:443
D/ActivityThread(11645): handleBindApplication:com.whatsapp
D/org.littleshoot.proxy.mitm.BouncyCastleSslEngineSource( 2897): [MoCuishle-0-ClientToProxyWorker-0] Host Name Verification is not supported, causes insecure HTTPS connection
D/ActivityThread(11645): setTargetHeapUtilization:0.75
D/org.littleshoot.proxy.mitm.BouncyCastleSslEngineSource( 2897): [MoCuishle-0-ClientToProxyWorker-0] Removed cipher TLS_DHE_RSA_WITH_AES_128_CBC_SHA
D/ActivityThread(11645): setTargetHeapMinFree:2097152
D/org.littleshoot.proxy.mitm.BouncyCastleSslEngineSource( 2897): [MoCuishle-0-ClientToProxyWorker-0] Enabled server cipher suites:
D/org.littleshoot.proxy.mitm.BouncyCastleSslEngineSource( 2897): [MoCuishle-0-ClientToProxyWorker-0] SSL_RSA_WITH_RC4_128_MD5
D/org.littleshoot.proxy.mitm.BouncyCastleSslEngineSource( 2897): [MoCuishle-0-ClientToProxyWorker-0] SSL_RSA_WITH_RC4_128_SHA
D/org.littleshoot.proxy.mitm.BouncyCastleSslEngineSource( 2897): [MoCuishle-0-ClientToProxyWorker-0] TLS_RSA_WITH_AES_128_CBC_SHA
D/org.littleshoot.proxy.mitm.BouncyCastleSslEngineSource( 2897): [MoCuishle-0-ClientToProxyWorker-0] TLS_DHE_DSS_WITH_AES_128_CBC_SHA
D/org.littleshoot.proxy.mitm.BouncyCastleSslEngineSource( 2897): [MoCuishle-0-ClientToProxyWorker-0] SSL_RSA_WITH_3DES_EDE_CBC_SHA
D/org.littleshoot.proxy.mitm.BouncyCastleSslEngineSource( 2897): [MoCuishle-0-ClientToProxyWorker-0] SSL_DHE_RSA_WITH_3DES_EDE_CBC_SHA
D/org.littleshoot.proxy.mitm.BouncyCastleSslEngineSource( 2897): [MoCuishle-0-ClientToProxyWorker-0] SSL_DHE_DSS_WITH_3DES_EDE_CBC_SHA
D/org.littleshoot.proxy.mitm.BouncyCastleSslEngineSource( 2897): [MoCuishle-0-ClientToProxyWorker-0] SSL_RSA_WITH_DES_CBC_SHA
D/org.littleshoot.proxy.mitm.BouncyCastleSslEngineSource( 2897): [MoCuishle-0-ClientToProxyWorker-0] SSL_DHE_RSA_WITH_DES_CBC_SHA
D/org.littleshoot.proxy.mitm.BouncyCastleSslEngineSource( 2897): [MoCuishle-0-ClientToProxyWorker-0] SSL_DHE_DSS_WITH_DES_CBC_SHA
D/org.littleshoot.proxy.mitm.BouncyCastleSslEngineSource( 2897): [MoCuishle-0-ClientToProxyWorker-0] SSL_RSA_EXPORT_WITH_RC4_40_MD5
D/org.littleshoot.proxy.mitm.BouncyCastleSslEngineSource( 2897): [MoCuishle-0-ClientToProxyWorker-0] SSL_RSA_EXPORT_WITH_DES40_CBC_SHA
D/org.littleshoot.proxy.mitm.BouncyCastleSslEngineSource( 2897): [MoCuishle-0-ClientToProxyWorker-0] SSL_DHE_RSA_EXPORT_WITH_DES40_CBC_SHA
D/org.littleshoot.proxy.mitm.BouncyCastleSslEngineSource( 2897): [MoCuishle-0-ClientToProxyWorker-0] SSL_DHE_DSS_EXPORT_WITH_DES40_CBC_SHA
D/org.littleshoot.proxy.impl.ClientToProxyConnection( 2897): [MoCuishle-0-ClientToProxyWorker-0] (AWAITING_INITIAL) [id: 0xf0297475, /127.0.0.1:39401 => /127.0.0.1:9090]: Stopped reading
D/org.littleshoot.proxy.impl.ProxyToServerConnection( 2897): [MoCuishle-0-ClientToProxyWorker-0] (DISCONNECTED): Processing connection flow step: CONNECTING
D/org.littleshoot.proxy.impl.ProxyToServerConnection( 2897): [MoCuishle-0-ClientToProxyWorker-0] (CONNECTING): Connecting to server with TCP
D/org.littleshoot.proxy.impl.ClientToProxyConnection( 2897): [MoCuishle-0-ClientToProxyWorker-0] (NEGOTIATING_CONNECT) [id: 0xf0297475, /127.0.0.1:39401 => /127.0.0.1:9090]: Reading: EmptyLastHttpContent
D/org.littleshoot.proxy.impl.ClientToProxyConnection( 2897): [MoCuishle-0-ClientToProxyWorker-0] (NEGOTIATING_CONNECT) [id: 0xf0297475, /127.0.0.1:39401 => /127.0.0.1:9090]: Attempted to read from connection that's in the process of negotiating an HTTP CONNECT.  This is probably the LastHttpContent of a chunked CONNECT.
D/org.littleshoot.proxy.impl.ProxyToServerConnection( 2897): [MoCuishle-0-ProxyToServerWorker-5] (CONNECTING) [id: 0x6ca7716c, /100.71.157.71:55898 => developer.cdn.mozilla.net/54.240.162.197:443]: ConnectionFlowStep succeeded
D/org.littleshoot.proxy.impl.ProxyToServerConnection( 2897): [MoCuishle-0-ProxyToServerWorker-5] (CONNECTING) [id: 0x6ca7716c, /100.71.157.71:55898 => developer.cdn.mozilla.net/54.240.162.197:443]: Processing connection flow step: HANDSHAKING
D/org.littleshoot.proxy.impl.ProxyToServerConnection( 2897): [MoCuishle-0-ProxyToServerWorker-5] (HANDSHAKING) [id: 0x6ca7716c, /100.71.157.71:55898 => developer.cdn.mozilla.net/54.240.162.197:443]: Enabling encryption with SSLEngine: com.android.org.conscrypt.SSLEngineImpl@4225b640
D/org.littleshoot.proxy.impl.ProxyToServerConnection( 2897): [MoCuishle-0-ProxyToServerWorker-5] (HANDSHAKING) [id: 0x6ca7716c, /100.71.157.71:55898 => developer.cdn.mozilla.net/54.240.162.197:443]: Connected
D/org.littleshoot.proxy.impl.ProxyToServerConnection( 2897): [MoCuishle-0-ProxyToServerWorker-5] (HANDSHAKING) [id: 0x6ca7716c, /100.71.157.71:55898 => developer.cdn.mozilla.net/54.240.162.197:443]: ConnectionFlowStep failed
D/org.littleshoot.proxy.impl.ProxyToServerConnection( 2897): javax.net.ssl.SSLException: Fatal alert received handshake_failure
D/org.littleshoot.proxy.impl.ProxyToServerConnection( 2897):    at com.android.org.conscrypt.SSLEngineImpl.unwrap(SSLEngineImpl.java:484) ~[na:0.0]
D/org.littleshoot.proxy.impl.ProxyToServerConnection( 2897):    at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:383) ~[na:0.0]
D/org.littleshoot.proxy.impl.ProxyToServerConnection( 2897):    at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1098) ~[na:0.0]
D/org.littleshoot.proxy.impl.ProxyToServerConnection( 2897):    at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:976) ~[na:0.0]
D/org.littleshoot.proxy.impl.ProxyToServerConnection( 2897):    at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:912) ~[na:0.0]
D/org.littleshoot.proxy.impl.ProxyToServerConnection( 2897):    at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:369) ~[na:0.0]
D/org.littleshoot.proxy.impl.ProxyToServerConnection( 2897):    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:244) ~[na:0.0]
D/org.littleshoot.proxy.impl.ProxyToServerConnection( 2897):    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:307) ~[na:0.0]
D/org.littleshoot.proxy.impl.ProxyToServerConnection( 2897):    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:293) ~[na:0.0]
D/org.littleshoot.proxy.impl.ProxyToServerConnection( 2897):    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:840) ~[na:0.0]
D/org.littleshoot.proxy.impl.ProxyToServerConnection( 2897):    at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131) ~[na:0.0]
D/org.littleshoot.proxy.impl.ProxyToServerConnection( 2897):    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511) ~[na:0.0]
D/org.littleshoot.proxy.impl.ProxyToServerConnection( 2897):    at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:430) ~[na:0.0]
D/org.littleshoot.proxy.impl.ProxyToServerConnection( 2897):    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:384) ~[na:0.0]
D/org.littleshoot.proxy.impl.ProxyToServerConnection( 2897):    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354) ~[na:0.0]
D/org.littleshoot.proxy.impl.ProxyToServerConnection( 2897):    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112) ~[na:0.0]
D/org.littleshoot.proxy.impl.ProxyToServerConnection( 2897):    at java.lang.Thread.run(Thread.java:841) ~[na:0.0]
D/org.littleshoot.proxy.impl.ClientToProxyConnection( 2897): [MoCuishle-0-ProxyToServerWorker-5] (NEGOTIATING_CONNECT) [id: 0xf0297475, /127.0.0.1:39401 => /127.0.0.1:9090]: All servers have finished attempting to connect, resuming reading from client.
D/org.littleshoot.proxy.impl.ClientToProxyConnection( 2897): [MoCuishle-0-ProxyToServerWorker-5] (NEGOTIATING_CONNECT) [id: 0xf0297475, /127.0.0.1:39401 => /127.0.0.1:9090]: Resumed reading
I/org.littleshoot.proxy.impl.ProxyToServerConnection( 2897): [MoCuishle-0-ProxyToServerWorker-5] (HANDSHAKING) [id: 0x6ca7716c, /100.71.157.71:55898 :> developer.cdn.mozilla.net/54.240.162.197:443]: Connection to upstream server failed
I/org.littleshoot.proxy.impl.ProxyToServerConnection( 2897): javax.net.ssl.SSLException: Fatal alert received handshake_failure
I/org.littleshoot.proxy.impl.ProxyToServerConnection( 2897):    at com.android.org.conscrypt.SSLEngineImpl.unwrap(SSLEngineImpl.java:484) ~[na:0.0]
I/org.littleshoot.proxy.impl.ProxyToServerConnection( 2897):    at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:383) ~[na:0.0]
I/org.littleshoot.proxy.impl.ProxyToServerConnection( 2897):    at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1098) ~[na:0.0]
I/org.littleshoot.proxy.impl.ProxyToServerConnection( 2897):    at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:976) ~[na:0.0]
I/org.littleshoot.proxy.impl.ProxyToServerConnection( 2897):    at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:912) ~[na:0.0]
I/org.littleshoot.proxy.impl.ProxyToServerConnection( 2897):    at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:369) ~[na:0.0]
I/org.littleshoot.proxy.impl.ProxyToServerConnection( 2897):    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:244) ~[na:0.0]
I/org.littleshoot.proxy.impl.ProxyToServerConnection( 2897):    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:307) ~[na:0.0]
I/org.littleshoot.proxy.impl.ProxyToServerConnection( 2897):    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:293) ~[na:0.0]
I/org.littleshoot.proxy.impl.ProxyToServerConnection( 2897):    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:840) ~[na:0.0]
I/org.littleshoot.proxy.impl.ProxyToServerConnection( 2897):    at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131) ~[na:0.0]
I/org.littleshoot.proxy.impl.ProxyToServerConnection( 2897):    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511) ~[na:0.0]
I/org.littleshoot.proxy.impl.ProxyToServerConnection( 2897):    at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:430) ~[na:0.0]
I/org.littleshoot.proxy.impl.ProxyToServerConnection( 2897):    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:384) ~[na:0.0]
I/org.littleshoot.proxy.impl.ProxyToServerConnection( 2897):    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354) ~[na:0.0]
I/org.littleshoot.proxy.impl.ProxyToServerConnection( 2897):    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112) ~[na:0.0]
I/org.littleshoot.proxy.impl.ProxyToServerConnection( 2897):    at java.lang.Thread.run(Thread.java:841) ~[na:0.0]
D/org.littleshoot.proxy.impl.ClientToProxyConnection( 2897): [MoCuishle-0-ProxyToServerWorker-5] (NEGOTIATING_CONNECT) [id: 0xf0297475, /127.0.0.1:39401 => /127.0.0.1:9090]: Connection to upstream server or chained proxy failed: developer.cdn.mozilla.net/54.240.162.197:443.  Last state before failure: HANDSHAKING
</pre>

**Comment by jekh** [comment]
Is it possible to get more SSL debug info using the `-Djavax.net.debug=all` JVM parameter on Android?

**Comment by ganskef** [comment]
No sadly. I could print out debug lines in Netty. Or I could give a modified a trust or key manager into.

**Comment by ganskef** [comment]
I do not use LittleProxy / Netty on Android anymore...
