### ISSUE TITLE
Error assembling root CA while using own custom certificate

### ISSUE THREAD

**Issue by mattsjk** [ganskef/LittleProxy-mitm#20]
I am using littleproxy-mitm as a maven dependency in my custom java 8 application that I am using as a chained proxy service within my organization to facilitate with single sign on into an enterprise application that utilizes AD and ADFS services in a hybrid mode (cloud + on-site).

Everything is working well and my proxy service is able to handle the http and Secure http (https) requests and forward them to the organization's proxy server.

The only issue that I have is for https requests, due to the certificate impersonation within the proxy service using MITM, we are getting a certificate error or untrusted certificate error in the browser. To overcome this issue, I have purchased a valid certificate and am trying to tell the application to use the valid trusted certificate to impersonate the certificates for the https requests.

This is the littleprxy-mitm code that I am using to initialise the usage of my trusted cert:
HttpProxyServer proxyServer = DefaultHttpProxyServer.bootstrap()
.withAddress(new InetSocketAddress(localHostIP, localPort))
.withManInTheMiddle(new CertificateSniffingMitmManager(
                            new Authority(new File("./<trusted_certifcate_name>.pfx")
                                    ,"my_app_proxy_service_name"
                                    ,"<my trusted cert password>".toCharArray()
                                    ,"<my trusted cert cn>"
                                    ,"<my trusted cert org>"
                                    ,"<my trusted cert org unit>"
                                    ,"DigiCert Inc"
                                    ,"www.digicert.com")))

But I keep getting a "RootCertificateException" saying "Errors during assembling root CA" although in the log, it says that the  "org.littleshoot.proxy.mitm.BouncyCastleSslEngineSource - Created root certificate authority key store in 858ms"

And due to the exception, I am unable to start up the java application.

I also tried running the application by providing the keystore details
-Djavax.net.ssl.trustStore="<JRE_HOME>\lib\security\cacerts" -Djavax.net.ssl.trustStorePassword="<truststore password>"

and also tried creating a new truststore

but none of the above approaches seem to be helping with the custom cert being loaded into the root CA.

Any help or guidance would really help
Mattsjk

**Comment by mattsjk** [comment]
Managed to sort the CA certificate loading issue - it was due to the filepath to the certificate file provided. In the new File() call, include the file path and also rename the cert to use the my_app_proxy_service_name with a .p12 extension.

Even after loading the cert, the browser still complains about the non-trusted cert. Trying to figure out how to get that working. It is not possible to load the public key for every user (browser). Will need to figure another way to get the app proxy to handle the certificate impersonation

**Comment by mattsjk** [comment]
I have got the application to use my trusted cert and is working fine except that that impersonated cert is now not being liked by the browsers. We are investigating this and will update once it is all sorted. I will close this issue once we have it all working.

**Comment by ganskef** [comment]
Hi @mattsjk I'm late, sorry. Do you have a question yet?

Please, have a look at https://github.com/ganskef/shortcircuit-proxy/blob/master/src/main/java/de/ganskef/tls/MitmCertificate.java and its usage to compare. It's inspired by OkHttp merged with the logic of LittleProxy-mitm. You should be able to create all you need easily like this:

```java
        MitmCertificate root = new MitmCertificate.RootBuilder().alias("amc-ca").organization("MATHEMA")
                .commonName("AMC-Example").password("password".toCharArray()).build();
        MitmCertificate.exportPem(new File("amc-ca.pem"), root.certificate);
        MitmCertificate fake = new MitmCertificate.FakeBuilder() //
                .issuedBy(root) //
                .commonName("localhost") //
                .duration(365) //
                .build();
        MitmCertificate.exportPem(new File("localhost.pem"), fake.certificate);

        KeyStore keystore = KeyStore.getInstance("PKCS12");
        keystore.load(null, null);
        keystore.setKeyEntry("amc-localhost", fake.keyPair.getPrivate(), "password".toCharArray(),
                new Certificate[] { fake.certificate });
        try (OutputStream os = new FileOutputStream(new File("amc-localhost.p12"))) {
            keystore.store(os, "password".toCharArray());
        }
```
 * `amc-ca.p12` is a Certificate Authoritiy needed to sign certificates (must be trusted)
 * `amc-localhost.p12` is a server certificate with CN `localhost` to install it in the server
 * `amc-ca.pem` is the Certificate Authorities public key only to be imported/trusted by the clients

**Comment by ganskef** [comment]
If you won't use a custom cert imported in all the clients, I can't help you. I argue (and hope!) you won't be able to get a cheap Certificate Authority trusted by every client easily. This should never happens since it breaks TLS at all.

**Comment by mattsjk** [comment]
We have a valid trusted certificate that will be trusted by the clients. I have successfully managed to load the certificate and everything is working as required except that the generated cert did not have the correct purpose. The cert was generated as a default web server cert and I realised that as it is acting as a proxy service and impersonating the other certs, it is part of the certification path and not the end entity on the cert chain - hence the browser is complaining that the cert is not performing the intended purposes. I believe I can close this issue here as the remaining problem is not related to the code, but just managing the right certificate.

**Comment by ganskef** [comment]
@mattsjk Thank you for sharing your experiences! I haven't expected such behavior. A regular browser is accepting a connection to a server intercepted (TLS faked) by the proxy with such a certificate chain? Okay, at least with a warning, but I would not be surprised if another browser or further version rejects this.
