### ISSUE TITLE
https Auth

### ISSUE THREAD

**Issue by JLeavell** [ganskef/LittleProxy-mitm#21]
Hello, I'm sure that this is probably something dumb, but I've gotten the http proxy all setup with just the basic instructions. Now, I'm trying to auth ssl websites, but I'm having dificulties with getting that portion to run. Is there any way that someone could help?

**Comment by mattsjk** [comment]
I have a similar app and it is almost working except that the SSL certs that are impersonated using our trusted cert is not being liked by the browser and we are investigating the issue currently. Let me know if you need any specific details and I am happy to share the info.

**Comment by ganskef** [comment]
Hi @JLeavell, please tell me more about the authorization. Is it a public site? Do you have an example?
