### ISSUE TITLE
DH 502bits

### ISSUE THREAD

**Issue by hnubility** [ganskef/LittleProxy-mitm#29]
s->session->key_exchange_info = DH_num_bits(dh);   //  if (s->session->key_exchange_info < 1024) {    //   OPENSSL_PUT_ERROR(SSL, SSL_R_BAD_DH_P_LENGTH);     //  goto err;    // }

can not resolved https
debug dh.length is 512 not > 1024

**Comment by ganskef** [comment]
Sorry, this is not clear. Hmm... I had issues with CHACHA20 cipher suites, so I've included a pattern in `org.littleshoot.proxy.mitm.BouncyCastleSslEngineSource.filterWeakCipherSuites(SSLEngine)`. But actually every thing works for me so I've reverted this. Please reopen, if you can describe this better.
