### ISSUE TITLE
netty_proxy_client  branch compile error

### ISSUE THREAD

**Issue by pinghe** [ganskef/LittleProxy-mitm#3]
/src/main/java/org/littleshoot/proxy/mitm/HostNameMitmManager.java:[14,8]

**Comment by ganskef** [comment]
Sorry @pinghe if I've wasted your time. It should build with ganskef/LittleProxy master now.

If you're willing to to spend more time, please have a look at the ProxyClientNettyTest and my problems with it. Please have a look at io.netty.handler.proxy.ProxyHandlerTest, too. It shows how to configure a proxy with a lot of handlers in a chain.

**Comment by ganskef** [comment]
The commit refers to the wrong number, should be #2 unrecognized_name.
