### ISSUE TITLE
Ability to ignore hosts based on CONNECT request.

### ISSUE THREAD

**Issue by readefine** [ganskef/LittleProxy-mitm#32]
Hello,

I have implemented the MITM as your example shows.
I have implemented a HttpFiltersSourceAdapter that has the method filterRequest.
I was hoping that returning null from the method would stop the filtering for certain hosts like appl/facebook. But i think the impersonation phase is still used when exchanging certificates. 

How do I ignore hosts for use with apps that do their own SSL handshaking?

I have tried to make an alternative to the CertificateSniffing MitmManager. But i could not find a way to avoid returning a SSLEngine and thus skipping the interference.

So for some domains i would like the proxy to act as transparent.

**Comment by readefine** [comment]
I have used a number of HttpProxyServer instances, some transparent, some MITM to redirect traffic based on hostname.

**Comment by ganskef** [comment]
I'm using this method `HttpFiltersSourceAdapter.filterRequest(HttpRequest, ChannelHandlerContext)` too. This is the right location to make host/URL based decisions. You have to return an `HttpFilters` implementation like an `HttpFiltersAdapter` which contains **a lot** of hooks. This is the place to do nothing, modify the pipeline like add/remove inflater or aggregator, modify/create response contents, perhaps handle the handshake. Its up to you to have **different** filters to chose in the filters source. In my use case, an offline proxy, I use 6 filters using the `clientToProxyRequest(HttpObject)` method to answer responses or returning null to pass unmodified processing, additionally `serverToProxyResponse(HttpObject)` to write the contents in the cache. I'm not familiar with your conditions, sorry. You have to dig into LittleProxy and Netty. Anyway I hope this helps.
