### ISSUE TITLE
Certificate Unknown issue

### ISSUE THREAD

**Issue by arunkumarmn9** [ganskef/LittleProxy-mitm#36]
I'm using LittleProxy-mitm for testing my site. for HTTP it was working fine but for HTTPS getting the following error :
in proxy
```
javax.net.ssl.SSLException: Received fatal alert: certificate_unknown
138711 2019-07-04 11:17:21,003 ERROR [LittleProxy-0-ClientToProxyWorker-0] impl.ClientToProxyConnection - (NEGOTIATING_CONNECT) [id: 0x831e1554, L:0.0.0.0/0.0.0.0:9090 ! R:/127.0.0.1:51782]: Caught an exception on ClientToProxyConnection 
```
in browser(firefox)
**Software is Preventing Firefox From Safely Connecting to This Site**
 Error code: **MOZILLA_PKIX_ERROR_MITM_DETECTED**
 Certificate:
![Screenshot from 2019-07-04 11-30-12](https://user-images.githubusercontent.com/40020602/60643140-cc609f00-9e4f-11e9-96b8-a2d0e9d1d51c.png)

**Comment by ganskef** [comment]
First, I'm using LittleProxy-mitm every day with Mozilla browsers (69.0.1) and others. Please verify if you have imported the *right* PEM file in "Firefox" > "Preferences" > Button: "View Certificates..." > "Certificate Manager" > Tab: "Authorities" > Button: "Import...". The PEM file (littleproxy-mitm.pem) is created while launching the JAR the first time.

**Comment by vikasguptahk** [comment]
ers reliably. Unless explicitly requested, heap buffer will always be preferred to avoid potential system unstability.
14:01:41.476 [main] INFO  o.l.p.impl.DefaultHttpProxyServer - Starting proxy at address: /127.0.0.1:9093
14:01:41.496 [main] INFO  o.l.p.impl.DefaultHttpProxyServer - Proxy listening with TCP transport
14:01:41.498 [main] INFO  o.l.p.impl.DefaultHttpProxyServer - Proxy started at address: /127.0.0.1:9093
io.netty.handler.codec.DecoderException: javax.net.ssl.SSLHandshakeException: Received fatal alert: certificate_unknown
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:418)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:245)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:292)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:278)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:962)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
	at io.netty.channel.nio.NioEv

**Comment by HeartIsBeat** [comment]
@vikasguptahk Do you have resolved this question of "Received fatal alert: certificate_unknown"?
