### ISSUE TITLE
IOS Simulator 8.x

### ISSUE THREAD

**Issue by forestofrain** [ganskef/LittleProxy-mitm#6]
IOS 8.x does not like the expiration cert date to be grater than `Mon, 24 Jan 6084 02:07:59 GMT`. After setting `NOT_AFTER` to this, proxy works as expected. I couldn't find any documentation describing IOS having this date limitation.

I used epochcoverter to get the milliseconds
```
Epoch timestamp: 129827326079
Timestamp in milliseconds: 129827326079000
Human time (your time zone): January 23, 6084 at 7:07:59 PM MST
Human time (GMT): Mon, 24 Jan 6084 02:07:59 GMT
```

#### working

``` java
private static final Date NOT_AFTER = new Date(129827326079000L);
```
```
Epoch timestamp: 129827326079
Timestamp in milliseconds: 129827326079000
Human time (your time zone): January 23, 6084 at 7:07:59 PM MST
Human time (GMT): Mon, 24 Jan 6084 02:07:59 GMT
```
![safari working](https://cloud.githubusercontent.com/assets/914011/8535093/d41a72d0-23ff-11e5-8df4-b5999dd40a3e.png)

#### error
``` java
private static final Date NOT_AFTER = new Date(129827326080000L);
```
```
Epoch timestamp: 129827326080
Timestamp in milliseconds: 129827326080000
Human time (your time zone): January 23, 6084 at 7:08:00 PM MST
Human time (GMT): Mon, 24 Jan 6084 02:08:00 GMT
```
![safari ssl error](https://cloud.githubusercontent.com/assets/914011/8535186/a74f8e6a-2400-11e5-9f39-77abb64fa1a8.png)

**Comment by zerkz** [comment]
what mitm manager are you using?

**Comment by ganskef** [comment]
Thank you @forestofrain for the hint. I think, it's not necessary to set NOT_AFTER to the maximum possible value. In commit 218c152eeed1e24d7cbc279e40f5cb9937160254 it was hundred years in the future. It's taken from Netty io.netty.handler.ssl.util.SelfSignedCertificate:

    /** The maximum possible value in X.509 specification: 9999-12-31 23:59:59 */
    static final Date NOT_AFTER = new Date(253402300799000L);

@jamesdbloom: I've brought this into MockServer, too https://github.com/jamesdbloom/mockserver/pull/99

**Comment by ganskef** [comment]
A little How To: 
 * To use LittleProxy-mitm with an iOS client, you have to set ```.withAllowLocalOnly(false)``` in the bootstrap of your proxy. 
 * Send the .pem file with your Certificate Authority to your device and import it by double clicking in Mail. 
 * To configure the proxy klick your WLAN and configure the tab HTTP-PROXY manual at the bottom.
 * The WLAN-router must allow connections between connected devices. 

Now, the http and https traffic of your iOS device should be routed to your proxy application, running on an other computer.
