### ISSUE TITLE
how to 'proxy'?

### ISSUE THREAD

**Issue by vicApakau** [ganskef/LittleProxy-mitm#9]
I built it and can run it.
Pardon, but how do I proxy a site, lets say twitter.com or anything?

**Comment by ganskef** [comment]
Hi @vicApakau, while running the included Launcher class you have to set the clients proxy settings adress to localhost and port to 9090. Of course, this depends on the client. With Mozilla, for example, please have a look at this: https://support.mozilla.org/en-US/kb/advanced-panel-settings-in-firefox#w_connection
 * Click the **Connection** > **Settings...** button
 * Check **Manual proxy configuration**
 * Enter **HTTP-Proxy** and **Port**
 * Check **Use this proxy server for all protocols**

For now, if you get an URL with your browser, it's delivered via the proxy. Try to shut down the proxy to validate this.
